### ISSUE TITLE
[enhancement] Merge the files in the contract directory into the common directory.

### ISSUE THREAD

**Issue by jorchiu** [eclipse-ibeji/freyja#34]
## Description

Merge the files in the contract directory into the common directory to reduce bloat.

## Acceptance criteria

- [ ] The files in the contract directory are merged into the common directory.

**Comment by wilyle** [comment]
I'm closing this. I don't think we actually want to do this, the separation is nice with the latest plugin model

**Comment by wilyle** [comment]
Turns out this made things easier when doing some refactoring around adapters, so it's been done after all
