### ISSUE TITLE
[BUG] GRPC provider proxy has the consumer address hardcoded and should be configurable

### ISSUE THREAD

**Issue by ruifelixpereira** [eclipse-ibeji/freyja#50]
## Description

GRPC provider proxy has the consumer address hardcoded [here](https://github.com/eclipse-ibeji/freyja/blob/a07b03349d23b14d0c215ace341e05d9e4e5195e/provider_proxies/grpc/v1/src/grpc_provider_proxy.rs#L26) to `[::1]:60010` making it unusable if we need to run it inside Kubernetes.

## Acceptance criteria

- [ ] The GRPC provider proxy consumer address should be configurable (e.g., using a configuration file like in other components).

**Comment by wilyle** [comment]
Thanks for filing the bug. I think this could be related to both #17 and #19, though adding configuration would be a good intermediate step and would unblock this issue much faster than trying to solve either of the other two issues.

Note that I am on holiday this week so I will not be able to start work on this issue until next week (25 Sept). If you need to get unblocked in the meantime you can try forking this repo and changing the value in the code yourself

**Comment by wilyle** [comment]
This should be fixed now. Please refer to the [proxy's readme](https://github.com/eclipse-ibeji/freyja/blob/main/provider_proxies/grpc/v1/README.md) for information on how to configure the URL
