### ISSUE TITLE
[enhancement] GRPC configurable advertised consumer address

### ISSUE THREAD

**Issue by ruifelixpereira** [eclipse-ibeji/freyja#70]
## Description

When running Freyja as a pod using Kubernetes, usually it get a K8s service in front. In this case the `consumer_address` to start listening for requests [here](https://github.com/eclipse-ibeji/freyja/blob/2424bb10e407cd4cca00f79e7edbc49199ec55bd/provider_proxies/grpc/v1/src/grpc_provider_proxy.rs#89) must be different from the `consumer_address` that needs to be advertised to others [here](https://github.com/eclipse-ibeji/freyja/blob/2424bb10e407cd4cca00f79e7edbc49199ec55bd/provider_proxies/grpc/v1/src/grpc_provider_proxy.rs#113) and [here](https://github.com/eclipse-ibeji/freyja/blob/2424bb10e407cd4cca00f79e7edbc49199ec55bd/provider_proxies/grpc/v1/src/grpc_provider_proxy.rs#161), since it's this address that will be used for others to call the K8s service in front of the pod.

## Acceptance criteria

- [ ] Provide a new config `consumer_address_advertised` property that differs from the existing `consumer_address` for this purpose:
    ```
    pub struct Config {
        /// The set of config values
        pub consumer_address: String,
        pub consumer_address_advertised: String,
    }
    ```
    
    This is an example of what should be the configuration file:
    ```
    {
        "consumer_address": "0.0.0.0:60010",
        "consumer_address_advertised": "freyja-k8s-service:60010"
    }
    ```

- [ ] Change code [here](https://github.com/eclipse-ibeji/freyja/blob/2424bb10e407cd4cca00f79e7edbc49199ec55bd/provider_proxies/grpc/v1/src/grpc_provider_proxy.rs#113) from this:

    ```
    let consumer_uri = format!("http://{}", self.config.consumer_address); // Devskim: ignore DS137138
    ```
    to this
    ```
    let consumer_uri = format!("http://{}", self.config.consumer_address_advertise); // Devskim: ignore DS137138
    ```

- [ ] Change code [here](https://github.com/eclipse-ibeji/freyja/blob/2424bb10e407cd4cca00f79e7edbc49199ec55bd/provider_proxies/grpc/v1/src/grpc_provider_proxy.rs#161) from this:

    ```
    let consumer_uri = format!("http://{}", self.config.consumer_address); // Devskim: ignore DS137138
    ```
    to this
    ```
    let consumer_uri = format!("http://{}", self.config.consumer_address_advertised); // Devskim: ignore DS137138
    ```

**Comment by wilyle** [comment]
I've made this change with a few modifications, mostly to make this property optional and use the current config as the default
